name: Deploy Vite App to Hostinger

on:
  push:
    branches:
      - main   # triggers on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Vite app
      - name: Build Vite app
        run: npm run build

      # Step 5 (Optional, for testing FTP connection):
      - name: Upload test file to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.HOSTINGER_FTP_HOST }}
          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: ./test-deploy.txt
          server-dir: /home/u971141230/domains/7dotit.solutions/public_html/
          protocol: ftp

      # Step 6: Deploy built files to Hostinger
      - name: Deploy Vite build to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.HOSTINGER_FTP_HOST }}
          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: dist/                   # Vite build output
          server-dir: /home/u971141230/domains/7dotit.solutions/public_html/
          protocol: ftp
